In [8]:
import numpy as np
import pickle

In [9]:
npz_path = "/home/jmme425/mom/src/logs/drqn_mdp/train_episodes_mdp_1764569411.npz"
with np.load(npz_path, allow_pickle=True) as data1:
    episodes = data1["episodes"].tolist()   # list[dict]
    meta = data1["meta"].item()             # dict

print(len(episodes), meta)
print(episodes[0].keys())     

500 {'env': 'mdp', 'model': 'drqn', 'seed': 1, 'timestamp': 1764569411, 'source': 'train'}
dict_keys(['states', 'actions', 'rewards', 'dones', 'activations', 'total_reward', 'block'])


In [10]:
episodes[499]

{'states': [array([1., 0., 0.]), array([0., 0., 1.])],
 'actions': [1, 0],
 'rewards': [0.0, 1.0],
 'dones': [False, True],
 'activations': [array([-4.5714951e-03, -1.2204640e-02,  9.9336344e-01, -9.7143918e-01,
         -9.9170506e-01, -9.9443942e-01,  6.8197021e-04,  9.8340923e-01,
          9.8813945e-01,  9.8835802e-01,  9.9463445e-01,  1.4584149e-05,
         -9.8567408e-01,  9.8436588e-01,  9.9128306e-01, -9.8788774e-01,
         -9.9644059e-01,  3.9096454e-01, -9.7820199e-01, -9.8959142e-01,
         -8.5719913e-01,  7.5512677e-01,  9.9486357e-01,  9.9272221e-01,
          9.9049693e-01,  9.7732764e-01,  9.8527086e-01, -1.6040567e-02,
         -9.9490678e-01,  9.9511021e-01,  9.8251581e-01, -9.9493337e-01],
        dtype=float32),
  array([-4.5714951e-03, -1.2204640e-02,  9.9336344e-01, -9.7143918e-01,
         -9.9170506e-01, -9.9443942e-01,  6.8197021e-04,  9.8340923e-01,
          9.8813945e-01,  9.8835802e-01,  9.9463445e-01,  1.4584149e-05,
         -9.8567408e-01,  9.84365

-----------------------------------------------------------------------------------------------

In [25]:
npz_path = "logs/drqn_tmaze/eval_drqn_tmaze/drqn_tmaze_episodes_1761616750.npz"
with np.load(npz_path, allow_pickle=True) as data:
    episodes = data["episodes"].tolist()   # list[dict]
    meta = data["meta"].item()             # dict

print(len(episodes), meta)
print(episodes[0].keys())     

100 {'env': 'tmaze', 'model': 'drqn', 'timestamp': 1761616750}
dict_keys(['states', 'actions', 'activations', 'final_reward', 'done'])


In [26]:
episodes[0]

{'states': [array([1., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0.]),
  array([0., 0., 1., 0., 0.]),
  array([0., 1., 0., 0., 0.]),
  array([0., 1., 0., 0., 0.]),
  array([0., 0., 1., 0., 0.]),
  array([0., 1., 0., 0., 0.]),
  array([1., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0.])],
 'actions': [0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 'activations': [array([-4.0992647e-03,  6.7437991e-02, -2.0177148e-02,  9.9778855e-01,
          3.7052888e-02,  1.4014741e-02,  2.7674049e-04, -4.0888336e-01,
         -2.3522084e-06, -2.4116880e-04, -3.6704406e-02, -7.9509497e-02,
         -1.0310481e-02,  3.5710213e-01,  7.5361919e-01, -3.3715978e-02,
          1.0383256e-03, -1.9263949e-01, -5.9178787e-05,  2.0494057e-02,
          1.1105677e-03, -1.1071829e-02,  3.1882840e-01, -8.9252344e-04,
         -2.4556139e-04,  1.2684605e-02,  8.81